def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
     {paths: [process.argv[1]]},
   )", __dir__]).strip
end

# Move use_frameworks! instruction here
use_frameworks! :linkage => :static

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!


setup_permissions([
  'AppTrackingTransparency',
  # 'BluetoothPeripheral',
  # 'Calendars',
  'Camera',
  # 'Contacts',
  # 'FaceID',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'MediaLibrary',
  # 'Microphone',
  'Motion',
  # 'Notifications',
  # 'PhotoLibrary',
  'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'SpeechRecognition',
  'StoreKit'
])
# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# 
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
require_relative '../node_modules/react-native-permissions/scripts/setup'
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Believe' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'react-native-version-info', :path => '../node_modules/react-native-version-info'
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'react-native-fbsdk-next', :path => '../node_modules/react-native-fbsdk-next'
  # pod 'ReactNativeNavigation/Fabric', :path => "../node_modules/react-native-navigation"
  # pod 'React-Core', :path => '../node_modules/react-native'

  # use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
  #  :flipper_configuration => flipper_config,
# :flipper_configuration => FlipperConfigurationq.enabled(["Debug"], { 'Flipper' => '0.190.0' }),

    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  
  # use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
# use_frameworks!
def use_flipper!(versions = {}, configurations: ['Debug'])
  Pod::UI.warn "use_flipper is deprecated, use the flipper_configuration option in the use_react_native function"
  use_flipper_pods(versions, :configurations => configurations)
end
  
  # use_flipper!()
  # use_frameworks!
  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'
  pod 'react-native-branch', path: '../node_modules/react-native-branch'
  pod 'RNPurchases', :path => '../node_modules/react-native-purchases', :inhibit_warnings => true, :modular_headers => false
  target 'BelieveTests' do
    inherit! :complete
    # Pods for testing
  end

  

  
  post_install do |installer|

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
